### ISSUE TITLE
请问PandoraTraderConfig.xml 中MarketDataServer地址如何获得？

### ISSUE THREAD

**Issue by Tsan1024** [pegasusTrader/PandoraTrader#10]
![image](https://github.com/pegasusTrader/PandoraTrader/assets/127735596/86384088-a2b6-49e4-b391-f4c9be17cb08)

**Comment by pegasusTrader** [comment]
1，通过询问你的账户经纪商
2，通过你的账户软件商的ip地址
3，如果是Simnow的前置地址，可以直接到[Simnow](https://www.simnow.com.cn/product.action)网页查看

**Comment by Tsan1024** [comment]
好的，谢谢
