### ISSUE TITLE
ctp接口兼容

### ISSUE THREAD

**Issue by Tsan1024** [pegasusTrader/PandoraTrader#11]
您好，请问请问代码架构现在是只支持ctp 期货期权吗？a股港股的支持吗？

**Comment by pegasusTrader** [comment]
您好，目前这个代码框架是支持多个交易接口，比如CTP，QDP，飞马等期货交易柜台，都有适配，并在实盘上交易。
a股，港股接入需要适配对应的柜台API，目前没有开发和适配过，要接入支持修改复杂度不高，主要是接口适配开发。

**Comment by Tsan1024** [comment]
好的，谢谢
