### ISSUE TITLE
cwStrategys.lib有没有开源计划？

### ISSUE THREAD

**Issue by zhuzhenping** [pegasusTrader/PandoraTrader#4]
cwStrategys.lib没找到开源代码，没有开源？

**Comment by pegasusTrader** [comment]
cwStrategys.lib 可以全部开放，预期十一之前

**Comment by pegasusTrader** [comment]
> cwStrategys.lib没找到开源代码，没有开源？

cwStrategys.lib 可以全部开放，预期十一之前

**Comment by pegasusTrader** [comment]
> cwStrategys.lib没找到开源代码，没有开源？

cwStrategys.lib主要是一些功能性补充，对平台主体功能没有影响，故不用期待太高。
我自己的实盘交易策略，目前没有开放的计划。

**Comment by zhuzhenping** [comment]
软件功能强悍，给您点赞!
另外，剩余的cwCTPDLL.lib未来是否有开源计划？
