### ISSUE TITLE
Interface里的会考虑开源吗，希望可以做二次开发

### ISSUE THREAD

**Issue by 1wy** [pegasusTrader/PandoraTrader#6]

**Comment by pegasusTrader** [comment]
> _No description provided._
目前正在考虑这个情况。不过路一步步走

**Comment by pegasusTrader** [comment]
正商量着打算把interface中的代码开放

**Comment by 345161974** [comment]
> 正商量着打算把interface中的代码开放

三年了，大佬有计划开源interface了嘛？

**Comment by pegasusTrader** [comment]
> > 正商量着打算把interface中的代码开放
> 
> 三年了，大佬有计划开源interface了嘛？
感谢您对PandoraTrader的关注，目前打算邀请制，对于感兴趣的朋友，可以将自身情况以及参与项目意愿发送邮件到pandoratrader@163.com, 会尽快回复您的诉求。
