### ISSUE TITLE
develop_6_5_1分支debug编译过程中undefined reference to 

### ISSUE THREAD

**Issue by Tsan1024** [pegasusTrader/PandoraTrader#9]
/usr/bin/ld: CMakeFiles/PandoraTrader.dir/PandoraDemoStrategyTrader.cpp.o: in function `PriceServerThread()':
/home/tsand/cplusplus/PandoraTrader/PandoraTrade/PandoraDemoStrategyTrader.cpp:232: undefined reference to `cwFtdMdSpi::SubscribeMarketData(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)'
/usr/bin/ld: /home/tsand/cplusplus/PandoraTrader/PandoraTrade/../bin/Debug/libPandoraStrategy.a(cwStrategyDemo.cpp.o): in function `cwStrategyDemo::PriceUpdate(std::shared_ptr<cwFtdcDepthMarketDataField>)':
/home/tsand/cplusplus/PandoraTrader/PandoraStrategy/cwStrategyDemo.cpp:27: undefined reference to `cwBasicStrategy::GetPositionsAndActiveOrders(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::shared_ptr<CWPOSITIONFIELD>, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<CWPOSITIONFIELD> > > >&, std::map<ActiveEasyKey, std::shared_ptr<ORDERFIELD>, std::less<ActiveEasyKey>, std::allocator<std::pair<ActiveEasyKey const, std::shared_ptr<ORDERFIELD> > > >&)'
collect2: error: ld returned 1 exit status
make[2]: *** [PandoraTrade/CMakeFiles/PandoraTrader.dir/build.make:86: ../bin/Debug/PandoraTrader] Error 1
make[1]: *** [CMakeFiles/Makefile2:163: PandoraTrade/CMakeFiles/PandoraTrader.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by pegasusTrader** [comment]
这个问题是库链接问题，编译器输出的undefined ref在cwPandoraDll的静态库有提供。
您可以提供下使用环境（Windows, Ubuntu  还是别的Constos）的信息以便帮忙解决,主要是确保库版本一致即可。

**Comment by Tsan1024** [comment]
ubuntu20.04 版本

**Comment by Tsan1024** [comment]
谢谢版主，已解决，是链接库问题，换成ubuntu下的就可以了
